services:
  # agent
  agent:
    container_name: agent
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
      - MODE=agent
    tty: true
    volumes:
    - ./:/config
    depends_on:
      - rabbitmq
      - mongodb
      - ner_connector
      - chitchat_connector
      - odqa_connector
      - chitchat_odqa_connector
      - max_confidence_connector
      - test_formatter_connector

  #connectors
  ner_connector:
    container_name: ner_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=ner
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  chitchat_connector:
    container_name: chitchat_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=chitchat
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  odqa_connector:
    container_name: odqa_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=odqa
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  chitchat_odqa_connector:
    container_name: chitchat_odqa_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=chitchat_odqa
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  max_confidence_connector:
    container_name: max_confidence_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=max_confidence
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  test_formatter_connector:
    container_name: test_formatter_connector
    #image: deeppavlov/agent:transport
    build:
      context: ../../
      dockerfile: Dockerfile
    environment:
    - MODE=service
    - SERVICE_NAME=test_formatter
    volumes:
      - ./:/config
    tty: true
    depends_on:
    - rabbitmq

  # infrastructure
  mongodb:
    image: mongo:3.2.0
    command: mongod
    container_name: mongodb
    ports:
    - 11010:27017

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
    - 11011:5672
    - 11012:15672

version: '2.3'
