agent:
  name: 'dp-agent'

  services:
    annotators:
    - name: 'ner'
      stateful: false
    - name: 'sentiment'
      stateful: false
    - name: 'obscenity'
      stateful: false

    skill_selectors:
    - name: 'chitchat_odqa'
      stateful: false

    skills:
    - name: 'odqa'
      stateful: false
    - name: 'chitchat'
      stateful: false

    response_selectors: []

    postprocessors: []

transport:
  type: 'rabbitmq'
  timeout_sec: 30.0

  rabbitmq:
    host: 'localhost'
    port: 5672

service:
  name: 'service_name'
  instance_id: ''
  batch_size: 1
  remote_url: 'protocol://host:port/endpoint'

