agent_namespace: 'deeppavlov_agent'

agent:
  name: 'dp_agent'

  services:
    annotators:
    - name: 'ner'
      stateful: false
    - name: 'sentiment'
      stateful: false
    - name: 'obscenity'
      stateful: false

    skill_selectors:
    - name: 'chitchat_odqa'
      stateful: false

    skills:
    - name: 'odqa'
      stateful: false
    - name: 'chitchat'
      stateful: false

    response_selectors: []

    postprocessors: []

transport:
  type: 'rabbitmq'
  timeout_sec: 30.0

  rabbitmq:
    host: 'localhost'
    port: 5672

service:
  name: 'service_name'
  instance_id: ''
  batch_size: 1
  remote_url: 'protocol://host:port/endpoint'

logging:
  version: 1
  disable_existing_loggers: false
  loggers:
    core:
      level: 'INFO'
      propagate: true
      handlers: ['stderr']
  formatters:
    default:
      format: "%(asctime)s.%(msecs)d %(levelname)s in '%(name)s'['%(module)s'] at line %(lineno)d: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'default'
      filename: '~/dp_agent.log'
    stdout:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stdout'
    stderr:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stderr'