agent_namespace: 'deeppavlov_agent'

agent:
  name: 'dp_agent'
  response_timeout_sec: 10

  pipeline: {
    utterance_annotators: ['ner'],
    skill_selector: ['chitchat_odqa'],
    skills: ['chitchat', 'odqa'],
    response_selector: [],
    response_annotators: ['ner'],
    response_formatter: [],
  }

services:
  ner:
    batch_size: 5
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'deeppavlov_ner_stand'
      caller: 'default'
      url: 'https://7004.lnsigo.mipt.ru/answer'

  chitchat:
    batch_size: 5
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'agent_ranking_chitchat_prep'
      caller: 'default'
      url: 'http://127.0.0.1:5001/skill'

  odqa:
    batch_size: 1
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'deeppavlov_odqa_stand'
      caller: 'default'
      url: 'https://7012.lnsigo.mipt.ru/answer'

  chitchat_odqa:
    batch_size: 5
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'agent_chitchat_odqa_selector'
      caller: 'default'
      url: 'http://127.0.0.1:5002/skill'

database:
  host: '10.11.1.251'
  port: 10001

transport:
  type: 'rabbitmq'

  rabbitmq:
    host: '127.0.0.1'
    port: 10000
    login: 'guest'
    password: 'guest'
    virtualhost: '/'
