agent_namespace: 'deeppavlov_agent'

agent:
  name: 'dp_agent'
  response_timeout_sec: 10
  pipeline: [['ner'],
             ['chitchat']]

services:
  ner:
    batch_size: 5
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'deeppavlov_ner_stand'
      caller: 'default'
      url: 'http://127.0.0.1:5000/answer'

  chitchat:
    batch_size: 5
    infer_timeout_sec: 30.0

    connector_params:
      formatter: 'agent_ranking_chitchat_prep'
      caller: 'default'
      url: 'http://127.0.0.1:5001/skill'

database:
  host: '10.11.1.251'
  port: 10001

transport:
  type: 'rabbitmq'

  rabbitmq:
    host: '127.0.0.1'
    port: 10000
    login: 'guest'
    password: 'guest'
    virtualhost: '/'

logging:
  version: 1
  disable_existing_loggers: false
  loggers:
    core:
      level: 'INFO'
      propagate: true
      handlers: ['stderr']
  formatters:
    default:
      format: "%(asctime)s.%(msecs)d %(levelname)s in '%(name)s'['%(module)s'] at line %(lineno)d: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'default'
      filename: '~/dp_agent.log'
    stdout:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stdout'
    stderr:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stderr'