agent_namespace: 'deeppavlov_agent'

agent:
  name: 'dp_agent'
  response_timeout_sec: 30.0
  pipeline: ['ner', 'chitchat']

  services:
  - name: 'ner'
    stateful: false
  - name: 'chitchat'
    stateful: false

transport:
  type: 'rabbitmq'

  rabbitmq:
    host: 'localhost'
    port: 5672

service:
  name: 'service_name'
  instance_id: ''
  batch_size: 1
  infer_timeout_sec: 30.0
  remote_url: 'protocol://host:port/endpoint'

logging:
  version: 1
  disable_existing_loggers: false
  loggers:
    core:
      level: 'INFO'
      propagate: true
      handlers: ['stderr']
    agent_orange:
      level: 'INFO'
      propagate: true
      handlers: ['stderr']
  formatters:
    default:
      format: "%(asctime)s.%(msecs)d %(levelname)s in '%(name)s'['%(module)s'] at line %(lineno)d: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'default'
      filename: '~/dp_agent.log'
    stdout:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stdout'
    stderr:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stderr'