agent_namespace: 'deeppavlov_agent'

agent:
  name: 'dp_agent'
  response_timeout_sec: 3

  database:
    host: '10.11.1.251'
    port: 10001

  pipeline: [['ner', 'sentiment'],
             ['chitchat']]

  services:
  - name: 'ner'
    stateful: false

  - name: 'sentiment'
    stateful: false

  - name: 'chitchat'
    stateful: false

service:
  name: 'ner'
  instance_id: ''
  batch_size: 1
  infer_timeout_sec: 30.0

  connector_params:
    formatter: 'deeppavlov_ner'
    caller: 'default'
    url: 'http://192.168.10.221:5000/ner'

transport:
  type: 'rabbitmq'

  rabbitmq:
    host: '192.168.10.221'
    port: 10000
    login: 'guest'
    password: 'guest'
    virtualhost: '/'

logging:
  version: 1
  disable_existing_loggers: false
  loggers:
    core:
      level: 'INFO'
      propagate: true
      handlers: ['stderr']
    agent_orange:
      level: 'DEBUG'
      propagate: true
      handlers: ['stderr']
  formatters:
    default:
      format: "%(asctime)s.%(msecs)d %(levelname)s in '%(name)s'['%(module)s'] at line %(lineno)d: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"
  handlers:
    file:
      class: 'logging.FileHandler'
      level: 'DEBUG'
      formatter: 'default'
      filename: '~/dp_agent.log'
    stdout:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stdout'
    stderr:
      class: 'logging.StreamHandler'
      level: 'DEBUG'
      formatter: 'default'
      stream: 'ext://sys.stderr'